<a href="https://colab.research.google.com/github/19pa1a0299/AI-lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment No 1:Numpy [19pa1a0299]

1)Different ways to create a Numpy arrays

In [1]:
[ ]
import numpy as np
p=np.array([1,2,3])
print(p)

[1 2 3]


In [2]:
p=np.array([[1,2,3],[10,20,30]])
print(p)

[[ 1  2  3]
 [10 20 30]]


2) ADD,REMOVE, MODIFY array elements in array

Add

In [5]:
a=np.array([1,2,3])
b=np.append(a,[96,98,100])
print(b)

[  1   2   3  96  98 100]


Remove

In [6]:
x=np.delete(a,2)
print(x)

[1 2]


Modify

In [7]:
x[x<2]=-1
print(x)

[-1  2]


3) Arthematic operations on Numpy array [ ]

In [8]:
[ ]
import numpy as np
l=([9,8,7])
m=([7,8,9])
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)

[16 16 16]
[ 2  0 -2]
[63 64 63]
[1.28571429 1.         0.77777778]
[2 0 7]


4)slicing and iterating of numpy array

Slicing

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:8])

[2 3 4 5 6 7 8]


Iterating

In [19]:
for x in arr:
 print(x)

1
2
3
4
5
6
7
8


5) matrix operations on bumpy arrays

In [14]:
[ ]
import numpy as np
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
